### ISSUE TITLE
memorandum

### ISSUE THREAD

**Issue by UTaM0** [UTaM0/Ubuntu18.04-on-Hyper-V#1]
- Internal Switchの新規作成

Default SwitchからDHCPで割り当てられているipを固定ipにすれば解決かとおもいきやDefault Swithのip自体もホストOSの再起動で可変だったので、内部ネットワークのスイッチとしてInternal Switchを作成(プレフィックス16のipが割り当てられる)
*cmdで確認

**Comment by UTaM0** [comment]
- 仮想NICの新規作成

Internal Switchと疎通が取れるゲストOSの仮想NICを作成。固定ipを/etc/network/interfacesで設定してSSHできるか確認。

**Comment by UTaM0** [comment]
- ルーティングテーブルの修正

ip routeを確認したところdefault via ~がDefault SwitchとInternal Switchの2つ分あってインターネットと疎通ができなくなってしまったので静的ルーティングテーブルでInternal Switchの方を削除
*metricを変えれば削除しなくてもよさそうだけど今回は削除した

**Comment by UTaM0** [comment]
仮想NIC
`# ip link add eth1 type veth`
`# ip addr add [Internal Switchと同一ネットワークip] dev eth1`
`# ip link set eth1 up`

**Comment by UTaM0** [comment]
静的ipとルーティングテーブル修正
`# nano /etc/network/interfaces`
```
auto eth1
iface eth1 inet static
   ip address [Internal Switchと同一ネットワークip]
   netmask 255.255.0.0
   gateway [Internal Switchのip]
   post-up ip route del default via [Internal Switchのip] dev eth1
```

**Comment by UTaM0** [comment]
[参考資料]
https://qiita.com/tsuemura/items/3f8b310b062b36246252

[イメージ図]
![network architecture](https://github.com/UTaM0/Ubuntu18.04-on-Hyper-V/blob/main/images/UbuntuOnHyperV.png)

**Comment by UTaM0** [comment]
![UbuntuOnHyperV](https://user-images.githubusercontent.com/41279335/107722907-5c9ce080-6d23-11eb-9d93-e24d2baa6efb.png)

**Comment by UTaM0** [comment]
### [Ubuntu 20.04のやり方]

静的IPの設定方法(yamlファイル新規作成)
```
# nano /etc/netplan/99_config.yaml
```

```
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: true
    eth1:　　　　　　　　　　　　　　
      dhcp4: false
      dhcp6: false
      addresses: [169.254.100.101/16]
      gateway4: 169.254.224.228　　　　　
```

ルーティングテーブルの修正方法
networkd-dispattcherを使用

```
# nano /etc/networkd-dispattcher/routable.d/IntSW-DefRouteDown.sh
```

```
#!/bin/sh

# Only remove the default route on the second interface, e.g. eth1
[ "$IFACE" != eth1 ] && exit 0

# delete the default route for this interface
ip route del default dev eth1
```
